# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.SLM_core <- function(x, y) {
    .Call(`_STAT600_HW1_SLM_SLM_core`, x, y)
}

